name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Deploy Gatsby app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2.3.4

      - name: Setup Node
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 14

      - name: Install Node dependencies
        run: npm ci --no-audit --no-optional

      - name: Build app
        run: npm run build -- --prefix-paths

      - name: Publish app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
